// Code generated by entc, DO NOT EDIT.

package instruction

const (
	// Label holds the string label denoting the instruction type in the database.
	Label = "instruction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSentAt holds the string denoting the sentat field in the database.
	FieldSentAt = "sent_at"
	// EdgeAgent holds the string denoting the agent edge name in mutations.
	EdgeAgent = "agent"
	// EdgeAction holds the string denoting the action edge name in mutations.
	EdgeAction = "action"
	// EdgeBeacon holds the string denoting the beacon edge name in mutations.
	EdgeBeacon = "beacon"
	// Table holds the table name of the instruction in the database.
	Table = "instructions"
	// AgentTable is the table the holds the agent relation/edge.
	AgentTable = "instructions"
	// AgentInverseTable is the table name for the Agent entity.
	// It exists in this package in order to avoid circular dependency with the "agent" package.
	AgentInverseTable = "agents"
	// AgentColumn is the table column denoting the agent relation/edge.
	AgentColumn = "instruction_agent"
	// ActionTable is the table the holds the action relation/edge.
	ActionTable = "actions"
	// ActionInverseTable is the table name for the Action entity.
	// It exists in this package in order to avoid circular dependency with the "action" package.
	ActionInverseTable = "actions"
	// ActionColumn is the table column denoting the action relation/edge.
	ActionColumn = "instruction_action"
	// BeaconTable is the table the holds the beacon relation/edge.
	BeaconTable = "instructions"
	// BeaconInverseTable is the table name for the Beacon entity.
	// It exists in this package in order to avoid circular dependency with the "beacon" package.
	BeaconInverseTable = "beacons"
	// BeaconColumn is the table column denoting the beacon relation/edge.
	BeaconColumn = "beacon_instruction"
)

// Columns holds all SQL columns for instruction fields.
var Columns = []string{
	FieldID,
	FieldSentAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "instructions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"beacon_instruction",
	"instruction_agent",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
