// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BradHacker/titan/ent/agent"
	"github.com/BradHacker/titan/ent/heartbeat"
	"github.com/BradHacker/titan/ent/predicate"
)

// HeartbeatUpdate is the builder for updating Heartbeat entities.
type HeartbeatUpdate struct {
	config
	hooks    []Hook
	mutation *HeartbeatMutation
}

// Where adds a new predicate for the HeartbeatUpdate builder.
func (hu *HeartbeatUpdate) Where(ps ...predicate.Heartbeat) *HeartbeatUpdate {
	hu.mutation.predicates = append(hu.mutation.predicates, ps...)
	return hu
}

// SetSentAt sets the "sentAt" field.
func (hu *HeartbeatUpdate) SetSentAt(t time.Time) *HeartbeatUpdate {
	hu.mutation.SetSentAt(t)
	return hu
}

// SetReceivedAt sets the "receivedAt" field.
func (hu *HeartbeatUpdate) SetReceivedAt(t time.Time) *HeartbeatUpdate {
	hu.mutation.SetReceivedAt(t)
	return hu
}

// SetAgentID sets the "agent" edge to the Agent entity by ID.
func (hu *HeartbeatUpdate) SetAgentID(id int) *HeartbeatUpdate {
	hu.mutation.SetAgentID(id)
	return hu
}

// SetAgent sets the "agent" edge to the Agent entity.
func (hu *HeartbeatUpdate) SetAgent(a *Agent) *HeartbeatUpdate {
	return hu.SetAgentID(a.ID)
}

// Mutation returns the HeartbeatMutation object of the builder.
func (hu *HeartbeatUpdate) Mutation() *HeartbeatMutation {
	return hu.mutation
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (hu *HeartbeatUpdate) ClearAgent() *HeartbeatUpdate {
	hu.mutation.ClearAgent()
	return hu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HeartbeatUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(hu.hooks) == 0 {
		if err = hu.check(); err != nil {
			return 0, err
		}
		affected, err = hu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HeartbeatMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = hu.check(); err != nil {
				return 0, err
			}
			hu.mutation = mutation
			affected, err = hu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(hu.hooks) - 1; i >= 0; i-- {
			mut = hu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, hu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HeartbeatUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HeartbeatUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HeartbeatUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hu *HeartbeatUpdate) check() error {
	if _, ok := hu.mutation.AgentID(); hu.mutation.AgentCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"agent\"")
	}
	return nil
}

func (hu *HeartbeatUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   heartbeat.Table,
			Columns: heartbeat.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: heartbeat.FieldID,
			},
		},
	}
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hu.mutation.SentAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: heartbeat.FieldSentAt,
		})
	}
	if value, ok := hu.mutation.ReceivedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: heartbeat.FieldReceivedAt,
		})
	}
	if hu.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   heartbeat.AgentTable,
			Columns: []string{heartbeat.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: agent.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   heartbeat.AgentTable,
			Columns: []string{heartbeat.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: agent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{heartbeat.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// HeartbeatUpdateOne is the builder for updating a single Heartbeat entity.
type HeartbeatUpdateOne struct {
	config
	hooks    []Hook
	mutation *HeartbeatMutation
}

// SetSentAt sets the "sentAt" field.
func (huo *HeartbeatUpdateOne) SetSentAt(t time.Time) *HeartbeatUpdateOne {
	huo.mutation.SetSentAt(t)
	return huo
}

// SetReceivedAt sets the "receivedAt" field.
func (huo *HeartbeatUpdateOne) SetReceivedAt(t time.Time) *HeartbeatUpdateOne {
	huo.mutation.SetReceivedAt(t)
	return huo
}

// SetAgentID sets the "agent" edge to the Agent entity by ID.
func (huo *HeartbeatUpdateOne) SetAgentID(id int) *HeartbeatUpdateOne {
	huo.mutation.SetAgentID(id)
	return huo
}

// SetAgent sets the "agent" edge to the Agent entity.
func (huo *HeartbeatUpdateOne) SetAgent(a *Agent) *HeartbeatUpdateOne {
	return huo.SetAgentID(a.ID)
}

// Mutation returns the HeartbeatMutation object of the builder.
func (huo *HeartbeatUpdateOne) Mutation() *HeartbeatMutation {
	return huo.mutation
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (huo *HeartbeatUpdateOne) ClearAgent() *HeartbeatUpdateOne {
	huo.mutation.ClearAgent()
	return huo
}

// Save executes the query and returns the updated Heartbeat entity.
func (huo *HeartbeatUpdateOne) Save(ctx context.Context) (*Heartbeat, error) {
	var (
		err  error
		node *Heartbeat
	)
	if len(huo.hooks) == 0 {
		if err = huo.check(); err != nil {
			return nil, err
		}
		node, err = huo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HeartbeatMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = huo.check(); err != nil {
				return nil, err
			}
			huo.mutation = mutation
			node, err = huo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(huo.hooks) - 1; i >= 0; i-- {
			mut = huo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, huo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HeartbeatUpdateOne) SaveX(ctx context.Context) *Heartbeat {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HeartbeatUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HeartbeatUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (huo *HeartbeatUpdateOne) check() error {
	if _, ok := huo.mutation.AgentID(); huo.mutation.AgentCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"agent\"")
	}
	return nil
}

func (huo *HeartbeatUpdateOne) sqlSave(ctx context.Context) (_node *Heartbeat, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   heartbeat.Table,
			Columns: heartbeat.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: heartbeat.FieldID,
			},
		},
	}
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Heartbeat.ID for update")}
	}
	_spec.Node.ID.Value = id
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := huo.mutation.SentAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: heartbeat.FieldSentAt,
		})
	}
	if value, ok := huo.mutation.ReceivedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: heartbeat.FieldReceivedAt,
		})
	}
	if huo.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   heartbeat.AgentTable,
			Columns: []string{heartbeat.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: agent.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   heartbeat.AgentTable,
			Columns: []string{heartbeat.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: agent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Heartbeat{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{heartbeat.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
