// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BradHacker/titan/ent/agent"
	"github.com/BradHacker/titan/ent/heartbeat"
)

// HeartbeatCreate is the builder for creating a Heartbeat entity.
type HeartbeatCreate struct {
	config
	mutation *HeartbeatMutation
	hooks    []Hook
}

// SetSentAt sets the "sentAt" field.
func (hc *HeartbeatCreate) SetSentAt(t time.Time) *HeartbeatCreate {
	hc.mutation.SetSentAt(t)
	return hc
}

// SetReceivedAt sets the "receivedAt" field.
func (hc *HeartbeatCreate) SetReceivedAt(t time.Time) *HeartbeatCreate {
	hc.mutation.SetReceivedAt(t)
	return hc
}

// SetAgentID sets the "agent" edge to the Agent entity by ID.
func (hc *HeartbeatCreate) SetAgentID(id int) *HeartbeatCreate {
	hc.mutation.SetAgentID(id)
	return hc
}

// SetAgent sets the "agent" edge to the Agent entity.
func (hc *HeartbeatCreate) SetAgent(a *Agent) *HeartbeatCreate {
	return hc.SetAgentID(a.ID)
}

// Mutation returns the HeartbeatMutation object of the builder.
func (hc *HeartbeatCreate) Mutation() *HeartbeatMutation {
	return hc.mutation
}

// Save creates the Heartbeat in the database.
func (hc *HeartbeatCreate) Save(ctx context.Context) (*Heartbeat, error) {
	var (
		err  error
		node *Heartbeat
	)
	if len(hc.hooks) == 0 {
		if err = hc.check(); err != nil {
			return nil, err
		}
		node, err = hc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HeartbeatMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = hc.check(); err != nil {
				return nil, err
			}
			hc.mutation = mutation
			node, err = hc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(hc.hooks) - 1; i >= 0; i-- {
			mut = hc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, hc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HeartbeatCreate) SaveX(ctx context.Context) *Heartbeat {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (hc *HeartbeatCreate) check() error {
	if _, ok := hc.mutation.SentAt(); !ok {
		return &ValidationError{Name: "sentAt", err: errors.New("ent: missing required field \"sentAt\"")}
	}
	if _, ok := hc.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "receivedAt", err: errors.New("ent: missing required field \"receivedAt\"")}
	}
	if _, ok := hc.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent", err: errors.New("ent: missing required edge \"agent\"")}
	}
	return nil
}

func (hc *HeartbeatCreate) sqlSave(ctx context.Context) (*Heartbeat, error) {
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (hc *HeartbeatCreate) createSpec() (*Heartbeat, *sqlgraph.CreateSpec) {
	var (
		_node = &Heartbeat{config: hc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: heartbeat.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: heartbeat.FieldID,
			},
		}
	)
	if value, ok := hc.mutation.SentAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: heartbeat.FieldSentAt,
		})
		_node.SentAt = value
	}
	if value, ok := hc.mutation.ReceivedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: heartbeat.FieldReceivedAt,
		})
		_node.ReceivedAt = value
	}
	if nodes := hc.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   heartbeat.AgentTable,
			Columns: []string{heartbeat.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: agent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.heartbeat_agent = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HeartbeatCreateBulk is the builder for creating many Heartbeat entities in bulk.
type HeartbeatCreateBulk struct {
	config
	builders []*HeartbeatCreate
}

// Save creates the Heartbeat entities in the database.
func (hcb *HeartbeatCreateBulk) Save(ctx context.Context) ([]*Heartbeat, error) {
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Heartbeat, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HeartbeatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HeartbeatCreateBulk) SaveX(ctx context.Context) []*Heartbeat {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
