// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BradHacker/titan/ent/heartbeat"
	"github.com/BradHacker/titan/ent/predicate"
)

// HeartbeatDelete is the builder for deleting a Heartbeat entity.
type HeartbeatDelete struct {
	config
	hooks    []Hook
	mutation *HeartbeatMutation
}

// Where adds a new predicate to the HeartbeatDelete builder.
func (hd *HeartbeatDelete) Where(ps ...predicate.Heartbeat) *HeartbeatDelete {
	hd.mutation.predicates = append(hd.mutation.predicates, ps...)
	return hd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (hd *HeartbeatDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(hd.hooks) == 0 {
		affected, err = hd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HeartbeatMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			hd.mutation = mutation
			affected, err = hd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(hd.hooks) - 1; i >= 0; i-- {
			mut = hd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, hd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (hd *HeartbeatDelete) ExecX(ctx context.Context) int {
	n, err := hd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (hd *HeartbeatDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: heartbeat.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: heartbeat.FieldID,
			},
		},
	}
	if ps := hd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, hd.driver, _spec)
}

// HeartbeatDeleteOne is the builder for deleting a single Heartbeat entity.
type HeartbeatDeleteOne struct {
	hd *HeartbeatDelete
}

// Exec executes the deletion query.
func (hdo *HeartbeatDeleteOne) Exec(ctx context.Context) error {
	n, err := hdo.hd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{heartbeat.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (hdo *HeartbeatDeleteOne) ExecX(ctx context.Context) {
	hdo.hd.ExecX(ctx)
}
