// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BradHacker/titan/ent/action"
	"github.com/BradHacker/titan/ent/agent"
	"github.com/BradHacker/titan/ent/beacon"
	"github.com/BradHacker/titan/ent/instruction"
)

// InstructionCreate is the builder for creating a Instruction entity.
type InstructionCreate struct {
	config
	mutation *InstructionMutation
	hooks    []Hook
}

// SetSentAt sets the "sentAt" field.
func (ic *InstructionCreate) SetSentAt(t time.Time) *InstructionCreate {
	ic.mutation.SetSentAt(t)
	return ic
}

// SetAgentID sets the "agent" edge to the Agent entity by ID.
func (ic *InstructionCreate) SetAgentID(id int) *InstructionCreate {
	ic.mutation.SetAgentID(id)
	return ic
}

// SetAgent sets the "agent" edge to the Agent entity.
func (ic *InstructionCreate) SetAgent(a *Agent) *InstructionCreate {
	return ic.SetAgentID(a.ID)
}

// SetActionID sets the "action" edge to the Action entity by ID.
func (ic *InstructionCreate) SetActionID(id int) *InstructionCreate {
	ic.mutation.SetActionID(id)
	return ic
}

// SetAction sets the "action" edge to the Action entity.
func (ic *InstructionCreate) SetAction(a *Action) *InstructionCreate {
	return ic.SetActionID(a.ID)
}

// SetBeaconID sets the "beacon" edge to the Beacon entity by ID.
func (ic *InstructionCreate) SetBeaconID(id int) *InstructionCreate {
	ic.mutation.SetBeaconID(id)
	return ic
}

// SetNillableBeaconID sets the "beacon" edge to the Beacon entity by ID if the given value is not nil.
func (ic *InstructionCreate) SetNillableBeaconID(id *int) *InstructionCreate {
	if id != nil {
		ic = ic.SetBeaconID(*id)
	}
	return ic
}

// SetBeacon sets the "beacon" edge to the Beacon entity.
func (ic *InstructionCreate) SetBeacon(b *Beacon) *InstructionCreate {
	return ic.SetBeaconID(b.ID)
}

// Mutation returns the InstructionMutation object of the builder.
func (ic *InstructionCreate) Mutation() *InstructionMutation {
	return ic.mutation
}

// Save creates the Instruction in the database.
func (ic *InstructionCreate) Save(ctx context.Context) (*Instruction, error) {
	var (
		err  error
		node *Instruction
	)
	if len(ic.hooks) == 0 {
		if err = ic.check(); err != nil {
			return nil, err
		}
		node, err = ic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InstructionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ic.check(); err != nil {
				return nil, err
			}
			ic.mutation = mutation
			node, err = ic.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ic.hooks) - 1; i >= 0; i-- {
			mut = ic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InstructionCreate) SaveX(ctx context.Context) *Instruction {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (ic *InstructionCreate) check() error {
	if _, ok := ic.mutation.SentAt(); !ok {
		return &ValidationError{Name: "sentAt", err: errors.New("ent: missing required field \"sentAt\"")}
	}
	if _, ok := ic.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent", err: errors.New("ent: missing required edge \"agent\"")}
	}
	if _, ok := ic.mutation.ActionID(); !ok {
		return &ValidationError{Name: "action", err: errors.New("ent: missing required edge \"action\"")}
	}
	return nil
}

func (ic *InstructionCreate) sqlSave(ctx context.Context) (*Instruction, error) {
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ic *InstructionCreate) createSpec() (*Instruction, *sqlgraph.CreateSpec) {
	var (
		_node = &Instruction{config: ic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: instruction.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: instruction.FieldID,
			},
		}
	)
	if value, ok := ic.mutation.SentAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: instruction.FieldSentAt,
		})
		_node.SentAt = value
	}
	if nodes := ic.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   instruction.AgentTable,
			Columns: []string{instruction.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: agent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.ActionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   instruction.ActionTable,
			Columns: []string{instruction.ActionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: action.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.BeaconIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   instruction.BeaconTable,
			Columns: []string{instruction.BeaconColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: beacon.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.beacon_instruction = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InstructionCreateBulk is the builder for creating many Instruction entities in bulk.
type InstructionCreateBulk struct {
	config
	builders []*InstructionCreate
}

// Save creates the Instruction entities in the database.
func (icb *InstructionCreateBulk) Save(ctx context.Context) ([]*Instruction, error) {
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Instruction, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InstructionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *InstructionCreateBulk) SaveX(ctx context.Context) []*Instruction {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
