// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Action is the predicate function for action builders.
type Action func(*sql.Selector)

// Agent is the predicate function for agent builders.
type Agent func(*sql.Selector)

// Beacon is the predicate function for beacon builders.
type Beacon func(*sql.Selector)

// Heartbeat is the predicate function for heartbeat builders.
type Heartbeat func(*sql.Selector)

// Instruction is the predicate function for instruction builders.
type Instruction func(*sql.Selector)
